name: image-quality-assessment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - matplotlib
  - pillow
  - scikit-image
  - flask
  - flask-cors
  - requests
  - pip:
    - opencv-python
    - rawpy